gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#a7c080"
      - "bold"
    inactiveBorderColor:
      - "#475258"
    searchingActiveBorderColor:
      - "#a7c080"
      - "bold"
    optionsTextColor:
      - "#7fbbb3"
    selectedLineBgColor:
      - "#2d353b"
    cherryPickedCommitFgColor:
      - "#7fbbb3"
    cherryPickedCommitBgColor:
      - "#d699b6"
    markedBaseCommitFgColor:
      - "#7fbbb3"
    markedBaseCommitBgColor:
      - "#dbbc7f"
    unstagedChangesColor:
      - "#e67e80"
    defaultFgColor:
      - "#d3c6aa"
