[Appearance]
color_scheme_path=/usr/share/qt6ct/colors/darker.conf
custom_palette=false
style=Fusion

[Fonts]
fixed=@Variant(\0\0\0@\0\0\04\x13\0M\0a\0p\0l\0e\0 \0M\0o\0n\0o\0 \0N\0L\0 \0N\0F\0 \0C\0N\0\0\0\xd\xff\xff\xff\xff\x05\x01\x02\x10)
general=@Variant(\0\0\0@\0\0\04\x13\0M\0a\0p\0l\0e\0 \0M\0o\0n\0o\0 \0N\0L\0 \0N\0F\0 \0C\0N\0\0\0\xd\xff\xff\xff\xff\x05\x01\x02\x10)

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
cursor_flash_time=1000
dialog_buttons_have_icons=1
double_click_interval=400
gui_effects=@Invalid()
menus_have_icons=true
stylesheets=@Invalid()

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x3\xb3\0\0\x4\x5\0\0\0\0\0\0\0\0\0\0\x3\xb3\0\0\x4\x5\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x3\xb3\0\0\x4\x5)
